app = "golangapi"

[build]
  # 可空白，除非你有特殊 build image 設定

[env]
  PORT = "80"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443