name: Build and Test Go App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENV_FILE: .env.prod
      PORT: 80 # 給 docker-compose.yml 用

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Go binary
        run: go build -v ./cmd/api

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker compose -f docker-compose.yml --env-file .env.prod build
